[package]
name = "slixmpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jid = "0.12"
pyo3 = { version = "0.23", features = ["extension-module"] }

[lib]
name = "jid"
crate-type = ["cdylib"]
path = "slixmpp/jid.rs"
