[pytest]
testpaths = tests/
asyncio_default_fixture_loop_scope = function
asyncio_mode = auto

markers =
    e2e: end-to-end tests requiring pyjabber
    slow: slow tests

filterwarnings =
    # SPADE closes the event loop when stopping the container, generating a conflict with pytest when
    # it tries to close the loop again
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore:.*Event loop is closed*:RuntimeWarning
