when:
  event: [ tag ]

steps:
  build-and-publish:
    image: ghcr.io/pyo3/maturin
    environment:
      TOKEN:
        from_secret: codeberg_package_nicoco
    commands:
    - maturin publish -i $TAG --username nicoco --password $TOKEN --repository-url https://codeberg.org/api/packages/poezio/pypi/ --no-sdist

matrix:
  TAG:
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
    - "3.13"
